/**
 * Custom Icon Chat Plugin for Side Server
 * Allows Leaders (&) and Admins (~) to assign custom userlist icons
 * using PostgreSQL persistence and config/custom.css.
 *
 * Note: Your server must be registered for custom icons to work.
 * Note: Custom icons currently do not display in the userlist on the Preact client
 *       because it does not assign user-specific IDs to userlist elements.
 */

import { Utils, FS } from '../../../lib';
import { PG } from '../../lib/postgres';
import { SSUtils } from '../../lib/ss-utils';
import { CUSTOM_ICONS_TABLE } from './database';

const CONFIG_PATH = 'config/custom.css' as const;
const START_TAG = '/* CUSTOM ICONS START */';
const END_TAG = '/* CUSTOM ICONS END */';

export interface CustomIconRow {
	user_id: string;
	name: string;
	url: string;
	set_by: string;
}

export interface CustomIconItem {
	userId: string;
	name: string;
	url: string;
	setBy: string;
}

const getIconTable = () => PG.getTable<CustomIconRow>(CUSTOM_ICONS_TABLE, 'user_id');

// In-memory cache of users' custom icons
const iconCache = new Map<string, CustomIconItem>();

function generateCSS(userid: string, url: string): string {
	const selector = `[id$="-userlist-user-${userid}"]`;
	return `${selector} {\n\tbackground: url("${url}") right no-repeat !important;\n\tbackground-size: 33px 32px !important;\n}`;
}

function generateCSSBlock(iconList: CustomIconItem[]): string {
	const rules: string[] = [
		START_TAG,
		`/*************************************************************`,
		` * CUSTOM USERLIST ICONS`,
		` * Auto-generated by the /customicon chat plugin.`,
		` *************************************************************/`,
	];

	for (const item of iconList) {
		rules.push(
			`/* User: ${item.name} (${item.userId}) */`,
			generateCSS(item.userId, item.url) + '\n'
		);
	}

	rules.push(
		END_TAG
	);

	return rules.join('\n');
}

async function initCustomIcons(): Promise<void> {
	try {
		const rows = await getIconTable().select();
		iconCache.clear();

		for (const row of rows) {
			const id = toID(row.user_id);
			const item: CustomIconItem = {
				userId: id,
				name: row.name,
				url: row.url,
				setBy: row.set_by,
			};
			iconCache.set(id, item);
		}
	} catch (err: unknown) {
		const message = err instanceof Error ? err.message : String(err);
		Monitor.warn(`[CustomIcon] Failed to load icons from PostgreSQL: ${message}`);
	}
}

export const CustomIconManager = {
	async setIcon(targetUser: string, url: string, setBy: string): Promise<CustomIconItem> {
		const id = toID(targetUser);
		if (!id || id.length > 18) {
			throw new Chat.ErrorMessage(`The username '${targetUser}' is invalid.`);
		}

		if (!url.startsWith('http://') && !url.startsWith('https://')) {
			throw new Chat.ErrorMessage(`The URL must start with http:// or https://.`);
		}

		const userObj = Users.getExact(targetUser);
		const name = userObj?.name || targetUser.trim();

		const item: CustomIconItem = {
			userId: id,
			name,
			url: url.trim(),
			setBy,
		};

		iconCache.set(id, item);

		await getIconTable().upsert({
			user_id: id,
			name,
			url: item.url,
			set_by: setBy,
		}, ['user_id']);

		await this.updateCSS();
		return item;
	},

	async deleteIcon(targetUser: string): Promise<boolean> {
		const id = toID(targetUser);
		if (!id || !iconCache.has(id)) return false;

		iconCache.delete(id);

		await getIconTable().deleteById(id);
		await this.updateCSS();
		return true;
	},

	getIcon(targetUser: string): CustomIconItem | null {
		return iconCache.get(toID(targetUser)) || null;
	},

	getAll(): CustomIconItem[] {
		return Array.from(iconCache.values()).sort((a, b) => Utils.compare(a.name, b.name));
	},

	async updateCSS(): Promise<void> {
		const iconList = this.getAll();
		const block = generateCSSBlock(iconList);

		try {
			let css = await FS(CONFIG_PATH).readIfExists();
			if (!css.includes(START_TAG)) {
				css = css.trimEnd() ? `${css.trimEnd()}\n\n${block}\n` : `${block}\n`;
			} else {
				const startIndex = css.indexOf(START_TAG);
				const endIndex = css.indexOf(END_TAG) + END_TAG.length;
				css = `${css.slice(0, startIndex).trimEnd()}\n\n${block}\n\n${css.slice(endIndex).trimStart()}`.trim() + '\n';
			}

			await FS(CONFIG_PATH).safeWrite(css);
			await SSUtils.reloadCSS();
		} catch (err: unknown) {
			const message = err instanceof Error ? err.message : String(err);
			Monitor.warn(`[CustomIcon] Failed to update custom.css: ${message}`);
		}
	},
};

void initCustomIcons()
	.then(() => CustomIconManager.updateCSS())
	.catch(err => {
		const message = err instanceof Error ? err.message : String(err);
		Monitor.warn(`CustomIcon PG init failed: ${message}`);
	});

export const commands: Chat.ChatCommands = {
	ci: 'customicon',
	customicons: 'customicon',
	customicon: {
		set: 'add',
		async add(target, room, user) {
			this.checkCan('bypassall');
			const [rawUser, ...urlParts] = target.split(',');
			const url = urlParts.join(',').trim();
			if (!rawUser || !url) return this.parse('/customicon help');

			const targetId = toID(rawUser);
			if (!targetId || targetId.length > 18) {
				throw new Chat.ErrorMessage(`The username '${rawUser}' is invalid.`);
			}

			const result = await CustomIconManager.setIcon(rawUser, url, user.name);

			this.sendReply(
				`|html|Successfully updated the custom icon for ${SSUtils.nameColor(result.name, true)}.`
			);

			SSUtils.sendPM(targetId, `<div class="broadcast-green"><b>Your custom userlist icon has been updated!</b><br />It was set by ${user.name}. Refresh your client to see the changes.</div>`);
		},

		delete: 'remove',
		async remove(target, room, user) {
			this.checkCan('bypassall');
			const targetUser = target.trim();
			if (!targetUser) return this.parse('/customicon help');

			const targetId = toID(targetUser);
			if (!targetId) return this.parse('/customicon help');

			const deleted = await CustomIconManager.deleteIcon(targetId);
			if (!deleted) {
				throw new Chat.ErrorMessage(`The user '${targetUser}' doesn't have a custom icon to delete.`);
			}

			this.sendReply(`The custom icon for '${targetUser}' has been successfully removed.`);

			SSUtils.sendPM(targetId, `<div class="broadcast-red"><b>Your custom userlist icon has been removed.</b><br />Refresh your client to see the changes.</div>`);
		},

		show: 'view',
		view(target, room, user) {
			if (!this.runBroadcast()) return;
			const targetId = toID(target) || user.id;
			if (!targetId) return this.parse('/customicon help');

			const custom = CustomIconManager.getIcon(targetId);
			const targetUser = Users.getExact(target) || Users.getExact(targetId);
			const displayName = targetUser?.name || custom?.name || target || user.name;

			if (!custom) {
				return this.sendReply(
					`|html|The user ${SSUtils.nameColor(displayName, true)} doesn't have a custom icon.`
				);
			}

			this.sendReplyBox(
				`<center><h3>Custom Icon for ${SSUtils.nameColor(custom.name, true)}</h3></center><hr>` +
				`<b>Icon:</b> <img src="${custom.url}" width="33" height="32" style="vertical-align:middle;margin-left:4px;" /><br />` +
				`<b>URL:</b> <code>${custom.url}</code><br />` +
				`<b>Set by:</b> ${SSUtils.nameColor(custom.setBy, true)}`
			);
		},

		preview(target, room, user) {
			if (!this.runBroadcast()) return;
			const [rawUser, ...urlParts] = target.split(',');
			let targetName = rawUser.trim();
			let url = urlParts.join(',').trim();

			if (!url && targetName) {
				targetName = user.name;
				url = rawUser.trim();
			}

			if (!targetName || !url) return this.parse('/customicon help');

			const escapedName = Utils.escapeHTML(targetName);
			this.sendReplyBox(
				`<center><b>Custom Icon Preview</b></center><hr>` +
				`<b>Preview:</b> ${escapedName} <img src="${url}" width="33" height="32" style="vertical-align:middle;margin-left:4px;" /><br />` +
				`<b>URL:</b> <code>${url}</code>`
			);
		},

		list(target, room, user) {
			if (!this.runBroadcast()) return;

			const iconList = CustomIconManager.getAll();
			if (iconList.length === 0) {
				return this.sendReplyBox("There are currently no custom icons registered.");
			}

			const dataRows: string[][] = [];
			for (const item of iconList) {
				const imageBadge = `<img src="${item.url}" width="33" height="32" style="vertical-align:middle;" />`;

				dataRows.push([
					SSUtils.nameColor(item.name, true),
					`<center>${imageBadge}</center>`,
					`<center><code>${item.url}</code></center>`,
					`<center>${SSUtils.nameColor(item.setBy, true)}</center>`,
				]);
			}

			const html = SSUtils.Table(
				`Custom Icons (${iconList.length})`,
				["User", "Preview", "URL", "Set By"],
				dataRows
			);
			this.sendReply(`|html|${html}`);
		},

		async reload(target, room, user) {
			this.checkCan('bypassall');
			await CustomIconManager.updateCSS();
			this.sendReply("The custom icon CSS has been successfully regenerated and reloaded.");
		},

		''(target, room, user) {
			return this.parse('/customicon help');
		},

		help() {
			this.runBroadcast();
			this.sendReplyBox(
				`<center><b>Custom Icon Commands</b></center><hr>` +
				`<b>/customicon set [user], [image url]</b>: Set or update a user's custom userlist icon. (&, ~)<hr>` +
				`<b>/customicon delete [user]</b>: Remove a user's custom userlist icon. (&, ~)<hr>` +
				`<b>/customicon view (user)</b>: View the custom icon details for a specific user.<hr>` +
				`<b>/customicon preview (user), [image url]</b>: Preview what a custom icon will look like.<hr>` +
				`<b>/customicon list</b>: View a list of all registered custom icons.<hr>` +
				`<b>/customicon reload</b>: Regenerate and reload the custom CSS from the database. (&, ~)`
			);
		},
	},
};
