/**
 * Custom Color Chat Plugin for Side Server
 * Allows Leaders (&) and Admins (~) to assign custom username colors in the userlist and chat
 * using PostgreSQL persistence, SSUtils in-memory color mappings, and config/custom.css.
 *
 * Note: Your server must be registered for custom colors to work.
 * Note: Custom colors in the userlist currently do not work on the Preact client.
 */

import { Utils, FS } from '../../../lib';
import { PG } from '../../lib/postgres';
import { SSUtils } from '../../lib/ss-utils';
import { CUSTOM_COLORS_TABLE } from './database';

const CONFIG_PATH = 'config/custom.css' as const;
const START_TAG = '/* CUSTOM COLORS START */';
const END_TAG = '/* CUSTOM COLORS END */';

export interface CustomColorRow {
	user_id: string;
	name: string;
	color: string;
	set_by: string;
}

export interface CustomColorItem {
	userId: string;
	name: string;
	color: string;
	setBy: string;
}

const getColorTable = () => PG.getTable<CustomColorRow>(CUSTOM_COLORS_TABLE, 'user_id');

// In-memory cache of user custom colors
const colorCache = new Map<string, CustomColorItem>();

function parseHexColor(input: string): string | null {
	let hex = input.trim();
	if (hex.startsWith('#')) hex = hex.slice(1);
	if (/^[0-9a-fA-F]{6}$/.test(hex)) {
		return `#${hex.toLowerCase()}`;
	}
	if (/^[0-9a-fA-F]{3}$/.test(hex)) {
		const r = hex[0];
		const g = hex[1];
		const b = hex[2];
		return `#${r}${r}${g}${g}${b}${b}`.toLowerCase();
	}
	return null;
}

function generateCSS(userid: string, color: string): string {
	const selector = [
		`.chatmessage-${userid} strong`,
		`.chatmessage-${userid} .username`,
		`[id$="-userlist-user-${userid}"] button:not([data-away]) strong`,
		`[id$="-userlist-user-${userid}"] button:not([data-away]) em`,
		`[id$="-userlist-user-${userid}"] button:not([data-away]) span`,
	].join(',\n');
	return `${selector} {\n\tcolor: ${color} !important;\n}`;
}

function generateCSSBlock(colorList: CustomColorItem[]): string {
	const rules: string[] = [
		START_TAG,
		`/*************************************************************`,
		` * CUSTOM USERNAME COLORS`,
		` * Auto-generated by the /customcolor chat plugin.`,
		` *************************************************************/`,
	];

	for (const item of colorList) {
		rules.push(
			`/* User: ${item.name} (${item.userId}) */`,
			generateCSS(item.userId, item.color) + '\n'
		);
	}

	rules.push(
		END_TAG
	);

	return rules.join('\n');
}

async function initCustomColors(): Promise<void> {
	try {
		const rows = await getColorTable().select();
		colorCache.clear();

		for (const row of rows) {
			const id = toID(row.user_id);
			const item: CustomColorItem = {
				userId: id,
				name: row.name,
				color: row.color,
				setBy: row.set_by,
			};
			colorCache.set(id, item);
			SSUtils.customColors[id] = item.color;
		}
	} catch (err: unknown) {
		const message = err instanceof Error ? err.message : String(err);
		Monitor.warn(`[CustomColor] Failed to load colors from PostgreSQL: ${message}`);
	}
}

export const CustomColorManager = {
	async setColor(targetUser: string, rawColor: string, setBy: string): Promise<CustomColorItem> {
		const id = toID(targetUser);
		if (!id || id.length > 18) {
			throw new Chat.ErrorMessage(`The username '${targetUser}' is invalid.`);
		}

		const color = parseHexColor(rawColor);
		if (!color) {
			throw new Chat.ErrorMessage(
				`"${rawColor}" is not a valid hex color. Please provide a 3-digit or 6-digit hex code (e.g. #ff3366 or ff3366).`
			);
		}

		const userObj = Users.getExact(targetUser);
		const name = userObj?.name || targetUser.trim();

		const item: CustomColorItem = {
			userId: id,
			name,
			color,
			setBy,
		};

		colorCache.set(id, item);
		SSUtils.customColors[id] = color;

		await getColorTable().upsert({
			user_id: id,
			name,
			color,
			set_by: setBy,
		}, ['user_id']);

		await this.updateCSS();
		return item;
	},

	async deleteColor(targetUser: string): Promise<boolean> {
		const id = toID(targetUser);
		if (!id || !colorCache.has(id)) return false;

		colorCache.delete(id);
		delete SSUtils.customColors[id];

		await getColorTable().deleteById(id);
		await this.updateCSS();
		return true;
	},

	getColor(targetUser: string): CustomColorItem | null {
		return colorCache.get(toID(targetUser)) || null;
	},

	getAll(): CustomColorItem[] {
		return Array.from(colorCache.values()).sort((a, b) => Utils.compare(a.name, b.name));
	},

	async updateCSS(): Promise<void> {
		const colorList = this.getAll();
		const block = generateCSSBlock(colorList);

		try {
			let css = await FS(CONFIG_PATH).readIfExists();
			if (!css.includes(START_TAG)) {
				css = css.trimEnd() ? `${css.trimEnd()}\n\n${block}\n` : `${block}\n`;
			} else {
				const startIndex = css.indexOf(START_TAG);
				const endIndex = css.indexOf(END_TAG) + END_TAG.length;
				css = `${css.slice(0, startIndex).trimEnd()}\n\n${block}\n\n${css.slice(endIndex).trimStart()}`.trim() + '\n';
			}

			await FS(CONFIG_PATH).safeWrite(css);
			await SSUtils.reloadCSS();
		} catch (err: unknown) {
			const message = err instanceof Error ? err.message : String(err);
			Monitor.warn(`[CustomColor] Failed to update custom.css: ${message}`);
		}
	},
};

void initCustomColors()
	.then(() => CustomColorManager.updateCSS())
	.catch(err => {
		const message = err instanceof Error ? err.message : String(err);
		Monitor.warn(`CustomColor PG init failed: ${message}`);
	});

export const commands: Chat.ChatCommands = {
	cc: 'customcolor',
	customcolour: 'customcolor',
	customcolours: 'customcolor',
	customcolors: 'customcolor',
	customcolor: {
		set: 'add',
		async add(target, room, user) {
			this.checkCan('bypassall');
			const [rawUser, rawColor] = target.split(',').map(s => s.trim());
			if (!rawUser || !rawColor) return this.parse('/customcolor help');

			const targetId = toID(rawUser);
			if (!targetId || targetId.length > 18) {
				throw new Chat.ErrorMessage(`The username '${rawUser}' is invalid.`);
			}

			const result = await CustomColorManager.setColor(rawUser, rawColor, user.name);

			this.sendReply(
				`|html|Successfully updated the custom color for ${SSUtils.nameColor(result.name, true)} to ` +
				`<font color="${result.color}"><b>${result.color}</b></font>.`
			);

			SSUtils.sendPM(targetId, `<div class="broadcast-green"><b>Your custom color has been updated!</b><br />Your new color is <font color="${result.color}"><b>${result.color}</b></font> (set by ${user.name}). Refresh your client to see the changes.</div>`);
		},

		delete: 'remove',
		async remove(target, room, user) {
			this.checkCan('bypassall');
			const targetUser = target.trim();
			if (!targetUser) return this.parse('/customcolor help');

			const targetId = toID(targetUser);
			if (!targetId) return this.parse('/customcolor help');

			const deleted = await CustomColorManager.deleteColor(targetId);
			if (!deleted) {
				throw new Chat.ErrorMessage(`The user '${targetUser}' doesn't have a custom color to delete.`);
			}

			this.sendReply(`The custom color for '${targetUser}' has been successfully removed.`);

			SSUtils.sendPM(targetId, `<div class="broadcast-red"><b>Your custom color has been removed.</b><br />Refresh your client to see the changes.</div>`);
		},

		show: 'view',
		view(target, room, user) {
			if (!this.runBroadcast()) return;
			const targetId = toID(target) || user.id;
			if (!targetId) return this.parse('/customcolor help');

			const custom = CustomColorManager.getColor(targetId);
			const targetUser = Users.getExact(target) || Users.getExact(targetId);
			const displayName = targetUser?.name || custom?.name || target || user.name;

			if (!custom) {
				return this.sendReply(
					`|html|The user ${SSUtils.nameColor(displayName, true)} doesn't have a custom color ` +
					`(currently using the default hashed color: <code>${SSUtils.nameColor(displayName, false)}</code>).`
				);
			}

			this.sendReplyBox(
				`<center><h3>Custom Color for ${SSUtils.nameColor(custom.name, true)}</h3></center><hr>` +
				`<b>Color:</b> <font color="${custom.color}"><b>${custom.color}</b></font> ` +
				`<span style="display:inline-block;width:12px;height:12px;background-color:${custom.color};border:1px solid #555;vertical-align:middle;margin-left:4px;"></span><br />` +
				`<b>Set by:</b> ${SSUtils.nameColor(custom.setBy, true)}`
			);
		},

		preview(target, room, user) {
			if (!this.runBroadcast()) return;
			const [rawUser, rawColor] = target.split(',').map(s => s.trim());
			let targetName = rawUser;
			let colorStr = rawColor;

			if (!rawColor && rawUser) {
				targetName = user.name;
				colorStr = rawUser;
			}

			if (!targetName || !colorStr) return this.parse('/customcolor help');

			const color = parseHexColor(colorStr);
			if (!color) {
				throw new Chat.ErrorMessage(
					`"${colorStr}" is not a valid hex color. Please provide a 3-digit or 6-digit hex code (e.g. #ff3366 or ff3366).`
				);
			}

			const escapedName = Utils.escapeHTML(targetName);
			this.sendReplyBox(
				`<center><b>Custom Color Preview</b></center><hr>` +
				`<b>Preview:</b> <strong style="color:${color};">${escapedName}</strong> ` +
				`<span style="display:inline-block;width:12px;height:12px;background-color:${color};border:1px solid #555;vertical-align:middle;margin-left:4px;"></span><br />` +
				`<b>Hex:</b> <code>${color}</code>`
			);
		},

		list(target, room, user) {
			if (!this.runBroadcast()) return;

			const colorList = CustomColorManager.getAll();
			if (colorList.length === 0) {
				return this.sendReplyBox("There are currently no custom colors registered.");
			}

			const dataRows: string[][] = [];
			for (const item of colorList) {
				const colorBadge = `<span style="display:inline-block;width:12px;height:12px;background-color:${item.color};border:1px solid #555;vertical-align:middle;margin-right:4px;"></span>` +
					`<font color="${item.color}"><b>${item.color}</b></font>`;

				dataRows.push([
					SSUtils.nameColor(item.name, true),
					`<center>${colorBadge}</center>`,
					`<center><code>${item.color}</code></center>`,
					`<center>${SSUtils.nameColor(item.setBy, true)}</center>`,
				]);
			}

			const html = SSUtils.Table(
				`Custom Colors (${colorList.length})`,
				["User", "Preview", "Hex Code", "Set By"],
				dataRows
			);
			this.sendReply(`|html|${html}`);
		},

		async reload(target, room, user) {
			this.checkCan('bypassall');
			await CustomColorManager.updateCSS();
			this.sendReply("The custom color CSS has been successfully regenerated and reloaded.");
		},

		''(target, room, user) {
			return this.parse('/customcolor help');
		},

		help() {
			this.runBroadcast();
			this.sendReplyBox(
				`<center><b>Custom Color Commands</b></center><hr>` +
				`<b>/customcolor set [user], [hex color]</b>: Set or update a user's custom username color. (&, ~)<hr>` +
				`<b>/customcolor delete [user]</b>: Remove a user's custom username color. (&, ~)<hr>` +
				`<b>/customcolor view (user)</b>: View the custom color details for a specific user.<hr>` +
				`<b>/customcolor preview (user), [hex color]</b>: Preview what a custom color will look like.<hr>` +
				`<b>/customcolor list</b>: View a list of all registered custom colors.<hr>` +
				`<b>/customcolor reload</b>: Regenerate and reload the custom CSS from the database. (&, ~)`
			);
		},
	},
};
